import { CanvasConfig, Node } from './types';

export const CANVAS_PRESETS: Record<string, CanvasConfig> = {
  // Essential 10 garment presets with CAD-level precision
  "t-shirt": {
    unit: "px",
    width: 4500,
    height: 5400,
    dpi: 300,
    background: "transparent",
    showGrid: true,
    gridSize: 15,
    showRulers: true,
    showGuides: true,
    safeAreaPct: 8,
    bleedMm: 3,
    garmentType: "t-shirt",
    printArea: {
      x: 1125,
      y: 900,
      width: 2250,
      height: 2700,
    },
  },
  "hoodie": {
    unit: "px",
    width: 4500,
    height: 5100,
    dpi: 300,
    background: "transparent",
    showGrid: true,
    gridSize: 15,
    showRulers: true,
    showGuides: true,
    safeAreaPct: 8,
    bleedMm: 3,
    garmentType: "hoodie",
    printArea: {
      x: 1200,
      y: 1050,
      width: 2400,
      height: 3000,
    },
  },
  "cap": {
    unit: "px",
    width: 3600,
    height: 2700,
    dpi: 300,
    background: "transparent",
    showGrid: true,
    gridSize: 12,
    showRulers: true,
    showGuides: true,
    safeAreaPct: 12,
    bleedMm: 2,
    garmentType: "cap",
    printArea: {
      x: 900,
      y: 600,
      width: 1800,
      height: 1200,
    },
  },
  "crewneck": {
    unit: "px",
    width: 4500,
    height: 5100,
    dpi: 300,
    background: "transparent",
    showGrid: true,
    gridSize: 15,
    showRulers: true,
    showGuides: true,
    safeAreaPct: 8,
    bleedMm: 3,
    garmentType: "crewneck",
    printArea: {
      x: 1200,
      y: 975,
      width: 2400,
      height: 2850,
    },
  },
  "tote": {
    unit: "px",
    width: 3900,
    height: 3600,
    dpi: 300,
    background: "transparent",
    showGrid: true,
    gridSize: 12,
    showRulers: true,
    showGuides: true,
    safeAreaPct: 10,
    bleedMm: 2,
    garmentType: "tote",
    printArea: {
      x: 975,
      y: 900,
      width: 1950,
      height: 1800,
    },
  },
  "longsleeve": {
    unit: "px",
    width: 4500,
    height: 5400,
    dpi: 300,
    background: "transparent",
    showGrid: true,
    gridSize: 15,
    showRulers: true,
    showGuides: true,
    safeAreaPct: 8,
    bleedMm: 3,
    garmentType: "longsleeve",
    printArea: {
      x: 1125,
      y: 900,
      width: 2250,
      height: 2700,
    },
  },
  "polo": {
    unit: "px",
    width: 4500,
    height: 5400,
    dpi: 300,
    background: "transparent",
    showGrid: true,
    gridSize: 15,
    showRulers: true,
    showGuides: true,
    safeAreaPct: 8,
    bleedMm: 3,
    garmentType: "polo",
    printArea: {
      x: 1125,
      y: 900,
      width: 2250,
      height: 2700,
    },
  },
  "tank": {
    unit: "px",
    width: 4200,
    height: 4500,
    dpi: 300,
    background: "transparent",
    showGrid: true,
    gridSize: 15,
    showRulers: true,
    showGuides: true,
    safeAreaPct: 8,
    bleedMm: 3,
    garmentType: "tank",
    printArea: {
      x: 1050,
      y: 900,
      width: 2100,
      height: 2400,
    },
  },
  "bomber": {
    unit: "px",
    width: 4800,
    height: 5100,
    dpi: 300,
    background: "transparent",
    showGrid: true,
    gridSize: 15,
    showRulers: true,
    showGuides: true,
    safeAreaPct: 12,
    bleedMm: 3,
    garmentType: "bomber",
    printArea: {
      x: 1200,
      y: 1050,
      width: 2400,
      height: 2400,
    },
  },
  "beanie": {
    unit: "px",
    width: 3300,
    height: 2700,
    dpi: 300,
    background: "transparent",
    showGrid: true,
    gridSize: 12,
    showRulers: true,
    showGuides: true,
    safeAreaPct: 12,
    bleedMm: 2,
    garmentType: "beanie",
    printArea: {
      x: 825,
      y: 675,
      width: 1650,
      height: 1350,
    },
  },
};

export const COLOR_SWATCHES = [
  "#000000", "#FFFFFF", "#FF0000", "#00FF00", "#0000FF",
  "#FFFF00", "#FF00FF", "#00FFFF", "#FFA500", "#800080",
  "#FFC0CB", "#A52A2A", "#808080", "#000080", "#008000",
];

export const GOOGLE_FONTS = [
  "Inter", "Roboto", "Open Sans", "Lato", "Montserrat",
  "Oswald", "Source Sans Pro", "Raleway", "PT Sans", "Lora",
  "Nunito", "Playfair Display", "Merriweather", "Poppins", "Rubik",
  "Work Sans", "Fira Sans", "Noto Sans", "Ubuntu", "Muli",
  "Crimson Text", "Libre Baskerville", "Georgia", "Times New Roman", "Arial",
  "Helvetica", "Courier New", "Verdana", "Trebuchet MS", "Impact",
];

export const TEMPLATES: Record<string, Node[]> = {
  "Bold Centered Text": [
    {
      id: "template-text-1",
      type: "text",
      name: "Bold Text",
      x: 200,
      y: 300,
      width: 400,
      height: 80,
      rotation: 0,
      opacity: 1,
      text: "BOLD TEXT",
      fontFamily: "Inter",
      fontSize: 48,
      fontWeight: 700,
      lineHeight: 1.2,
      letterSpacing: 2,
      align: "center",
      fill: { type: "solid", color: "#000000" },
    } as Node,
  ],
  "Badge Design": [
    {
      id: "template-shape-1",
      type: "shape",
      name: "Badge Circle",
      x: 250,
      y: 250,
      width: 300,
      height: 300,
      rotation: 0,
      opacity: 1,
      shape: "circle",
      fill: { type: "solid", color: "#FF6B6B" },
      stroke: { color: "#FFFFFF", width: 4 },
    } as Node,
    {
      id: "template-text-2",
      type: "text",
      name: "Badge Text",
      x: 300,
      y: 380,
      width: 200,
      height: 40,
      rotation: 0,
      opacity: 1,
      text: "BADGE",
      fontFamily: "Oswald",
      fontSize: 24,
      fontWeight: 600,
      lineHeight: 1,
      letterSpacing: 1,
      align: "center",
      fill: { type: "solid", color: "#FFFFFF" },
    } as Node,
  ],
  "Stacked Arches": [
    {
      id: "template-text-3",
      type: "text",
      name: "Top Text",
      x: 200,
      y: 200,
      width: 400,
      height: 50,
      rotation: 0,
      opacity: 1,
      text: "VINTAGE",
      fontFamily: "Oswald",
      fontSize: 36,
      fontWeight: 400,
      lineHeight: 1,
      letterSpacing: 4,
      align: "center",
      fill: { type: "solid", color: "#8B4513" },
    } as Node,
    {
      id: "template-text-4",
      type: "text",
      name: "Bottom Text",
      x: 200,
      y: 450,
      width: 400,
      height: 50,
      rotation: 0,
      opacity: 1,
      text: "DESIGN",
      fontFamily: "Oswald",
      fontSize: 36,
      fontWeight: 400,
      lineHeight: 1,
      letterSpacing: 4,
      align: "center",
      fill: { type: "solid", color: "#8B4513" },
    } as Node,
  ],
};