import { CanvasConfig, Node } from './types';

export const CANVAS_PRESETS: Record<string, CanvasConfig> = {
  "T-Shirt": {
    unit: "px",
    width: 4500,
    height: 5400,
    dpi: 300,
    background: "transparent",
    showGrid: false,
    gridSize: 20,
    showRulers: true,
    showGuides: true,
    safeAreaPct: 10,
    bleedMm: 3,
  },
  "Hoodie": {
    unit: "px",
    width: 4500,
    height: 5100,
    dpi: 300,
    background: "transparent",
    showGrid: false,
    gridSize: 20,
    showRulers: true,
    showGuides: true,
    safeAreaPct: 10,
    bleedMm: 3,
  },
  "Tote Bag": {
    unit: "px",
    width: 3900,
    height: 3600,
    dpi: 300,
    background: "transparent",
    showGrid: false,
    gridSize: 20,
    showRulers: true,
    showGuides: true,
    safeAreaPct: 10,
    bleedMm: 3,
  },
  "Custom": {
    unit: "px",
    width: 1200,
    height: 1200,
    dpi: 300,
    background: "transparent",
    showGrid: false,
    gridSize: 20,
    showRulers: true,
    showGuides: true,
    safeAreaPct: 10,
    bleedMm: 3,
  },
};

export const COLOR_SWATCHES = [
  "#000000", "#FFFFFF", "#FF0000", "#00FF00", "#0000FF",
  "#FFFF00", "#FF00FF", "#00FFFF", "#FFA500", "#800080",
  "#FFC0CB", "#A52A2A", "#808080", "#000080", "#008000",
];

export const GOOGLE_FONTS = [
  "Inter", "Roboto", "Open Sans", "Lato", "Montserrat",
  "Oswald", "Source Sans Pro", "Raleway", "PT Sans", "Lora",
  "Nunito", "Playfair Display", "Merriweather", "Poppins", "Rubik",
  "Work Sans", "Fira Sans", "Noto Sans", "Ubuntu", "Muli",
  "Crimson Text", "Libre Baskerville", "Georgia", "Times New Roman", "Arial",
  "Helvetica", "Courier New", "Verdana", "Trebuchet MS", "Impact",
];

export const TEMPLATES: Record<string, Node[]> = {
  "Bold Centered Text": [
    {
      id: "template-text-1",
      type: "text",
      name: "Bold Text",
      x: 200,
      y: 300,
      width: 400,
      height: 80,
      rotation: 0,
      opacity: 1,
      text: "BOLD TEXT",
      fontFamily: "Inter",
      fontSize: 48,
      fontWeight: 700,
      lineHeight: 1.2,
      letterSpacing: 2,
      align: "center",
      fill: { type: "solid", color: "#000000" },
    } as Node,
  ],
  "Badge Design": [
    {
      id: "template-shape-1",
      type: "shape",
      name: "Badge Circle",
      x: 250,
      y: 250,
      width: 300,
      height: 300,
      rotation: 0,
      opacity: 1,
      shape: "circle",
      fill: { type: "solid", color: "#FF6B6B" },
      stroke: { color: "#FFFFFF", width: 4 },
    } as Node,
    {
      id: "template-text-2",
      type: "text",
      name: "Badge Text",
      x: 300,
      y: 380,
      width: 200,
      height: 40,
      rotation: 0,
      opacity: 1,
      text: "BADGE",
      fontFamily: "Oswald",
      fontSize: 24,
      fontWeight: 600,
      lineHeight: 1,
      letterSpacing: 1,
      align: "center",
      fill: { type: "solid", color: "#FFFFFF" },
    } as Node,
  ],
  "Stacked Arches": [
    {
      id: "template-text-3",
      type: "text",
      name: "Top Text",
      x: 200,
      y: 200,
      width: 400,
      height: 50,
      rotation: 0,
      opacity: 1,
      text: "VINTAGE",
      fontFamily: "Oswald",
      fontSize: 36,
      fontWeight: 400,
      lineHeight: 1,
      letterSpacing: 4,
      align: "center",
      fill: { type: "solid", color: "#8B4513" },
    } as Node,
    {
      id: "template-text-4",
      type: "text",
      name: "Bottom Text",
      x: 200,
      y: 450,
      width: 400,
      height: 50,
      rotation: 0,
      opacity: 1,
      text: "DESIGN",
      fontFamily: "Oswald",
      fontSize: 36,
      fontWeight: 400,
      lineHeight: 1,
      letterSpacing: 4,
      align: "center",
      fill: { type: "solid", color: "#8B4513" },
    } as Node,
  ],
};